### ISSUE TITLE
404 Error on BundleDownload for private repo

### ISSUE THREAD

**Issue by masyed** [aws/aws-codedeploy-agent#11]
Hi Guys,
I am getting this error on deployments. This is from the log:

ERROR [codedeploy-agent(26296)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandExecutor: Could not download bundle at 'https://api.github.com/repos/my_organisation/my_repo/tarball/my_comitt_id'. Server returned code 404 'Not Found'

This is a private repo, so i created a Personal Access Token with "repo" scope and added the Token ID to the "Github Token" field under the AWS CodeDeploy Service.

Still the error happens. I am not sure if the codedeploy-agent gets this Token ID injected to it by the service when the deployment is called?

Any help will be appreciated.

regards

**Comment by digitaldavenyc** [comment]
I am also having an issue with this. Any help on this would be awesome.

**Comment by ivarvermeulen** [comment]
Also experiencing the same issue.

**Comment by wwwpro** [comment]
I had the same problem. In my case, I had joined another organization and was trying to deploy a private repo in that organization. I was using my own credentials to connect to Github in the AWS Codedeploy console. 

I solved it by going to my profile settings in GitHub. Then, under the Applications tab, I had to grant authorization for the AWS CodeDeploy Application for the new organization I had joined.

**Comment by Jmcfar** [comment]
Hi,

The 404 may be caused by CodeDeploy not having proper credentials to your GitHub repository. When doing the initial set up, you will need to go to the CodeDeploy console and perform the Connect to GitHub process described under "Deploying Application Files from GitHub" in https://blogs.aws.amazon.com/application-management/post/Tx33XKAKURCCW83/Automatically-Deploy-from-GitHub-Using-AWS-CodeDeploy. 

If you set up the GitHub push hook without doing this, CodeDeploy will try to anonymously download your repository, which for private repos will result in the 404 error you posted above.
