### ISSUE TITLE
CodeDeploy deletes files not included in Git

### ISSUE THREAD

**Issue by kmgsoftware** [aws/aws-codedeploy-agent#148]
We have a CodePipeline set up which uses CodeDeploy to deploy the latest updates from our repository on GitHub to an EC2 instance. This works fine, except for one issue: everything we have in our `.gitignore` file is deleted from the server whenever a deployment is performed.

For instance, this is a WordPress site, so we have `wp-config.php` and `wp-content/uploads` excluded from the repository. When a deployment runs, it deletes these files rendering the site unusable.

Our desired behavior is for CodeDeploy to overwrite existing files, but also ignore any files/directories not included in the repository so they can remain untouched. By default there seems to be a step that "clears out" the deployment destination before adding the new files, but we need to skip that.

Is there any setting, either in the console or `appspec.yml`, which will allow us to make deployments without having anything deleted? It seems like this would be a very common use case...if we can't make deployments like this then I'll have to just do all our updates via SFTP, which is pretty lame.

**Comment by rohkat-aws** [comment]
@kmgsoftware this would be a bug ,but if you dont mind can you explain the use case a little better .because the agent is not supposed to touch any files other than the user mentioned ones. I dont think there is a default step which clears out the destination file before doing a deployment, But we can look at it in more detail. Apologies for the late reply.

**Comment by rohkat-aws** [comment]
havenot seen a response for a long time closing it
