### ISSUE TITLE
Rewrite in something that is not ruby?

### ISSUE THREAD

**Issue by sky87** [aws/aws-codedeploy-agent#156]
We are considering using `CodeDeploy` , but having to install ruby and running a ruby daemon on our production servers is a no starter.
Are there any plans for a rewrite in something more performant/less resource intensive like go?

**Comment by sky87** [comment]
@rohkat-aws From past experience, personally, I don't trust the ruby community (i.e. gems) and the interpreter/stdlib enough for me to have a ruby program that should run unnoticed in background on a product I'm in charge of.

Aside from my prejudice on Ruby and community in general, the fact that #32 has been open since 2015 is very worrying.

**Comment by woodhull** [comment]
We've been using CodeDeploy for a few years and I would definitely not recommend using it for new projects. 

It seems like it's a bit orphaned by AWS and they're very slow to make ux improvements, support new ubuntu versions properly, fix agent bugs, etc. 

That memory usage bug is par for the course. 

Here's my pet issue: https://github.com/aws/aws-codedeploy-agent/issues/36 that's been open since 2015 even though I expect it would be a minor change and dozens of people have up voted it.

**Comment by runningman84** [comment]
I hope the will reimplement it in some language like go without any dependencies.

**Comment by fleaz** [comment]
I don't care in what language this agent is written in. The thing I care about is the development speed of this tool. #32 is 4 years old, Ruby 2.5 ( and therefore Ubuntu LTS support) took ages and is still broken (#201), the last release was one year ago and there was the insane amount of ONE commit in 2019 in this projekt.

This is not a cool little side project from someone written in it's spare time, this is a fundamental part of the AWS ecosystem and a shitload of people pay thousands of dollar every month to a billion dollar company and I really can't understand how they can let this code rot for years.

Excuse my tone, but I really have no understanding for this...
