### ISSUE TITLE
Ubuntu 20.04 & CodeDeploy agent version 1.1.1

### ISSUE THREAD

**Issue by paulthorburn** [aws/aws-codedeploy-agent#257]
I have been waiting for the agent that supports Ubuntu 20 and just saw that the latest release added support so went to deploy it  and I have run into 2 issues.

1) The installation script https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install does not work on Ubuntu 20.04 so I had to manually build it
2) When i run the agent my console is being spammed every few seconds with the following message 'Version 2 of the Ruby SDK will enter maintenance mode as of November 20, 2020. To continue receiving service updates and new features, please upgrade to Version 3. More information can be found here: https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/' 

Is there a way to suppress the warning?

**Comment by Helen1987** [comment]
1. @paulthorburn we had to rollback version 1.1.1, so it is not available via install script installation. We are planning to release version 1.1.2 (that support Ubuntu 20) as soon as we can. 
2. Could you clarify why do you need to disable warning? What issue do you face because of it?

**Comment by brblck** [comment]
The warning message you're seeing is begin generated by your version of Ruby, not the CodeDeploy agent. You can either upgrade to a newer version of Ruby that the agent supports (up to 2.7) or lower the log level and run without warnings in your Ruby runtime.

For the install script issue, I'm going to track this under https://github.com/aws/aws-codedeploy-agent/issues/264 since v1.1.1 of the CodeDeploy agent is actually deprecated.
