### ISSUE TITLE
codedeploy-local runs fine, but running it automatically through the pipeline it fails

### ISSUE THREAD

**Issue by adespain** [aws/aws-codedeploy-agent#262]
Hello,

I have a codedeploy-agent running on-premises and when I start the pipeline from the AWS console it fails.  The codedeploy-agent runs a script in scripts/run-test.sh.  This run-test.sh script executes a `docker-compose -f docker-compose-test.yml` command but fails with: `[stderr].FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-test.yml'`

I can run codedeploy-local and it will run the script just fine.  I also tried puting in the absolute path for the docker-compose-test.yml file and it fails with a different error saying it can't read the variable that is found in the .env file for docker-compose.  Does anyone know what I may be doing wrong?  

Here is the section from my appspec.yml file: 
```
  ApplicationStart:
    - location: scripts/run-test.sh    
      timeout: 300
```
`less /opt/codedeploy-agent/.version agent_version: OFFICIAL_1.1.2-1855_deb`

This is running on ubuntu 16.04

docker-compose is version: `docker-compose version 1.26.2, build eefe0d31`

**Comment by brblck** [comment]
This isn't really related to the CodeDeploy agent but for the `docker-compose -f docker-compose-test.yml` command to work, your `docker-compose-test.yml` file would need to be present in the same folder as `scripts/run-test.sh`. I would wager the issue here is just an incorrect path or relative reference.

Are you able to share the contents of the folder? Or the contents of `scripts/run-test.sh`?

**Comment by adespain** [comment]
You were right I had to change the PWD and then it worked.  Thanks for the response!
