### ISSUE TITLE
uninitialized constant Zip::File

### ISSUE THREAD

**Issue by PurrBiscuit** [aws/aws-codedeploy-agent#29]
I'm not sure if this is the where I should be filing this issue but I've been getting an `uninitialized constant Zip::File` error during the `DownloadBundle` event when trying to do a deploy from a .zip file through CodeDeploy.  I'm able to successfully deploy from a .tar.gz file without issue...as well as deploy directly through github directly.

I'm trying to use a Jenkins/AWS CodeDeploy plugin that compresses to a .zip before uploading to s3, otherwise I'd just use .tar.gz.

**Comment by suryanarayanan** [comment]
Hi,
Can you tell me your agent type (rpm/deb/msi) and version? To get the version you can do
RPM:
rpm -q codedeploy-agent
DEB:
dpkg -l codedeploy-agent
MSI:
Description from the service explorer.

**Comment by PurrBiscuit** [comment]
Hi, thanks for the quick response.  I'm not downloading the codedeploy-agent from a package source but rather through the chef aws-codedeploy-agent cookbook.  Looks like it's pulling the latest version on master from this repo.

https://github.com/continuousphp/aws-codedeploy-agent/blob/master/definitions/manual_installer.rb#L10

**Comment by suryanarayanan** [comment]
I notice a different gem named 'zip' used in https://github.com/continuousphp/aws-codedeploy-agent/blob/master/definitions/manual_installer.rb#L10 whereas the codedeploy-agent uses 'rubyzip' https://github.com/aws/aws-codedeploy-agent/blob/master/codedeploy_agent-1.1.0.gemspec

If you are using this in production, I would suggest to use a stable release rather than the head of the codedeploy-agent master branch. You can find the releases under https://github.com/aws/aws-codedeploy-agent/releases

**Comment by PurrBiscuit** [comment]
It seems like it's an issue with how the cookbook handles the gem and ruby installation.  I'm going to go ahead and close out the issue here.  Thanks for the quick responses.

I'm going to rework the cookbook a little and will include that recommendation to use the latest stable release vs what's on master.
