### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by OmriSama** [aws/aws-codedeploy-agent#318]
The project seems completely dead. The only Ruby version being seemingly tested against is 2.3.8 which is long EOL. Code coverage is <50%, and I don't see the authors or maintainers responding to any recent issues... Is this agent going to be updated? Replaced?

**Comment by mwjones-aws** [comment]
Yes, this project is still active. We have a release planned for May 2022.

**Comment by OmriSama** [comment]
@mwjones-aws It's May 31st and there still hasn't been a release. Is it postponed?

**Comment by mwjones-aws** [comment]
Yes, now targeting end of June

**Comment by mpdude** [comment]
Heads up: End of June approaching

**Comment by philstrong** [comment]
Behind the scenes, we've been dramatically improved our release and testing process to raise the bar for our customers. Due to the amount of work involved, our new target release date is September 2022. With the improved automation and confidence in our tests, our release velocity will increase. 

Appreciate the patience

**Comment by mpdude** [comment]
@philstrong, @mwjones-aws and @keithcyu,

as you are probably aware (see https://github.com/aws/aws-codedeploy-agent/issues/301#issuecomment-1124810261 for an example), there are a few people here who have a personal interest in making sure you can roll out the agent on various and/or up-to-date platforms and distros, and who are willing to help and contribute.

Given that the agent code is already open sourced here, maybe you can also publish the files necessary to do the packaging for various distros (e. g. `debian/` for `.deb` files)? Maybe the community can help with scripting/automation to make more frequent or snapshot releases possible. 

Additionally, this would improve transparency – it's good to hear that you are actively working on this, but your efforts currently are not visible, since there has been no progress in this repo here for a  year. Maybe we can change that 🍻 .

**Comment by philstrong** [comment]
Agreed, we have a visibility problem. It would be ideal to include the packaging code, so the community can create their own builds. We perform unit tests, signing and integration tests, among other things, in other repos that aren't on GitHub. In part b/c it's testing our services that interact with the agent. Having said that, we do have the ability to perform unsigned builds from our machines. 

We treat this repo as a mirror of our internal git repository, we can do a better job syncing those, so it's obvious where we're making changes between releases.

**Comment by mpdude** [comment]
> We treat this repo as a mirror of our internal git repository, we can do a better job syncing those, so it's obvious where we're making changes between releases.

I was already assuming this. The problem with this "throwing things over the fence once in a while" approach is that it is not easy for outside people to contribute (assuming you're interested in that): You don't see how changes flow back, and its also not easy for you to integrate outside changes and avoid merge conflicts if the community does not see the current code.

Looking forward to see what you can change to improve that 🚀

**Comment by fleaz** [comment]
> Behind the scenes, we've been dramatically improved our release and testing process

No offense, but we literally heard the exact same excuse over two years ago...

https://github.com/aws/aws-codedeploy-agent/issues/239#issuecomment-630527490

**Comment by kochul2000** [comment]
AWS team should at least warn this issue at the `System manager Distributor`! I wasted my time with a quietly failing distributor. finally I found this honey pot and now I totally understood that CodeDeploy Agent is practically abandoned state.

**Comment by sapphirecat** [comment]
Hi, just checking in.  It's been over 45 days since the last comment, and even longer since the "end of June" with no updates (neither here, nor on #301.)  What's the current plan?

**Comment by fleaz** [comment]
> Hi, just checking in. It's been over 45 days since the last comment, and even longer since the "end of June" with no updates (neither here, nor on #301.) What's the current plan?

`our new target release date is September 2022.`

Just scroll a few comments further up

**Comment by sapphirecat** [comment]
Thanks, but I would still like to know what the current status is.  Should I expect a September release, or are we looking at December now?

**Comment by grant-veepshosting** [comment]
@mwjones-aws Is this issue fixed in the fresh v1.4.0 release? I can't see it in the release notes anywhere.
Will there be another release in September to fix the Ubuntu 22.04 compatibility issue?

**Comment by fleaz** [comment]
@mwjones-aws Can't find 1.4.0 in here. What's the purpose of this repository if it doesn't represent the current state of the code?

**Comment by mwjones-aws** [comment]
We'll commit it today or tomorrow

**Comment by t0shiii** [comment]
PR for 1.4.0 release can be found here: https://github.com/aws/aws-codedeploy-agent/pull/332

**Comment by fleaz** [comment]
> We have a release planned for May 2022.

> now targeting end of June

> our new target release date is September 2022

And now it's 2023... 😞

**Comment by mwjones-aws** [comment]
https://github.com/aws/aws-codedeploy-agent/issues/318#issuecomment-1252699982

Version 1.4.1 has been released since then. https://github.com/aws/aws-codedeploy-agent/issues/343

**Comment by fleaz** [comment]
> Version 1.4.1 has been released since then. #343

Bot neither 1.4.0 nor 1.4.1 fixed the Ruby3 incompatibility, so users are still stuck at Ubuntu 20.04 :(

**Comment by mwjones-aws** [comment]
> Bot neither 1.4.0 nor 1.4.1 fixed the Ruby3 incompatibility, so users are still stuck at Ubuntu 20.04 :(

I agree. We're tracking that specific effort on #301
