### ISSUE TITLE
Is AWS still actively maintaining this?

### ISSUE THREAD

**Issue by mpdude** [aws/aws-codedeploy-agent#324]
The last commit to the `master` branch was one year ago, and the last release was made in May 2021.

The person who was last maintaining the code or merged commits has no public GitHub activity for a year as well, and is no longer listed in the [AWS organisation](https://github.com/orgs/aws/people?query=vrr-21).

Hey AWS, are you still actively maintaining this? Or has the codebase been abandoned and should we start looking into alternatives?

**Comment by mpdude** [comment]
X-red #318 and https://github.com/aws/aws-codedeploy-agent/issues/301#issuecomment-1124810261

**Comment by keithcyu** [comment]
Hi @mpdude,

We have taken a deep look at our release and testing process internally and are making a few significant improvements to them to ensure we keep the bar high for our customers. Due to the amount of work involved we’re sorry to say that we have postponed our release date to September 2022. In the meantime we are continuing monitoring our Github issues.
