### ISSUE TITLE
CodeDeploy Agent 1.3.2 failing to install with Ruby 2.7.6 version

### ISSUE THREAD

**Issue by chandrapratapsingh007** [aws/aws-codedeploy-agent#333]
@mwjones-aws The issue still persists with the installation of the codedeploy-agent. In the screenshot, you can see that I have the Ruby 2.7.6 version installed and tried to install the code deploy agent version 1.3.2 but it's still failing.

![Screenshot from 2022-09-22 17-40-00](https://user-images.githubusercontent.com/80380177/191743034-a6700d6a-3edc-463d-9a51-bd03f057865a.png)

_Originally posted by @chandrapratapsingh007 in https://github.com/aws/aws-codedeploy-agent/issues/157#issuecomment-1254937134_

**Comment by t0shiii** [comment]
The CodeDeploy Agent Debian package uses the OS's package manager to handle the Ruby dependency.  This means you will need to install ruby via the apt package manager in order to install CodeDeploy Agent.  You can follow the instructions in our [documentation](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html)

If you are installing the agent via `apt` on Ubuntu 20.04, Ruby will be installed as a dependency.
